### ISSUE TITLE
No notification is sent when the last attribute of a collection is deleted

### ISSUE THREAD

**Issue by P-bibs** [P-bibs/codap-transformers#113]

**Comment by thomascastleman** [comment]
Hey has this been reported yet?

**Comment by P-bibs** [comment]
No I think I got sidetracked working on something else and now I can't remember why this was an issue (I'm not sure what functionality we need that this blocks)

**Comment by thomascastleman** [comment]
I think it's for attribute selectors, which need to remove attributes from the selectors as they're deleted, but cannot do so properly if we aren't notified for the last attribute in a collection.

**Comment by thomascastleman** [comment]
Also, updates for attribute deletion don't flow correctly if we aren't notified that the last attribute was deleted

**Comment by thomascastleman** [comment]
Reported [here](https://codap.concord.org/forums/topic/no-notification-sent-on-deletion-of-last-attribute-in-collection/).

**Comment by thomascastleman** [comment]
Fixed [here](https://github.com/concord-consortium/codap/commit/4e14f7f49ed7712a9263ab0a3f00be7070a7f102).
