### ISSUE TITLE
Deleted datasets are still cached

### ISSUE THREAD

**Issue by stardust66** [P-bibs/codap-transformers#132]

**Comment by stardust66** [comment]
This should be a simple issue, but attempting to invalidate the cache after a deletion causes a weird bug:
- Create a new dataset
- Use the copy transformer and select the new dataset in the dropdown
- Delete the new dataset
- Switch to partition

This crashes the plugin with the error "Unhandled Rejection (Error): Failed to get context New Dataset"

I suspect this is because useAttribute is called on the old context name after it was deleted. Since the context information is currently cached, this bug does not show up, but if we properly invalidate cached contexts after they get deleted, we can observe this bug.

**Comment by stardust66** [comment]
Since we fixed #131, I don't think the user can tell that the deleted contexts are still cached, so we can table this for now.

**Comment by thomascastleman** [comment]
Shouldn't we be able to fix this by fixing `useAttributes`? When the dataset is deleted, it should be removed from the context selector anyway so it shouldn't be called with a deleted dataset.

Then we could properly invalidate things in the cache upon deletion. Thoughts? @stardust66
