### ISSUE TITLE
Consider moving group-by transformer 

### ISSUE THREAD

**Issue by schanzer** [P-bibs/codap-transformers#225]
Currently, the "Group By" transformer is under the "Constructing" heading:
![image](https://user-images.githubusercontent.com/77126/146557359-6cd98dc0-6a11-4ecb-9336-db3ef2349fa7.png)

"Group By" might fit more logically in the "Restructuring" group.  The other transformers in "Constructing" are (a) the transformers that we lean most heavily on in the DS curriculum and (b) the only transformers that require students to use the CODAP design recipe.

If "Group By" stays in the top tier, I think teachers who use our curriculum will need to constantly field students' questions about it. Also, arguably, "Group by" is a form of "Restructuring"! (And yes, I recall that I had the opportunity to weigh in on these groupings; alas, these thoughts had not occurred to me then.)

**Comment by thomascastleman** [comment]
We can move out Group By but then there's the question of where Sort should end up.

If we add a new sort transformer (per #224) and thus have two, should we move both of those into a new "Sorting" or "Ordering" category? If not, where should they go?

@schanzer @shriram

**Comment by shriram** [comment]
I'm happy to defer to wherever @schanzer thinks this will work best. Of course, we have to first resolve the sort/order issue (#224).

**Comment by schanzer** [comment]
@thomascastleman Now that we're combining both, I think the only change needed is for "group by" to be moved to restructuring.
