### ISSUE TITLE
confusion about type contracts

### ISSUE THREAD

**Issue by thomascastleman** [P-bibs/codap-transformers#230]
Emmanuel indicated there was some confusion over what type contracts apply to, a formula or the transformer itself. Currently, contracts only appear over formulas and apply to the formulas and not transformers.

Is there a way we can make this fact clearer through the UI? Filter I think does the best job of this:

![filter-ui](https://user-images.githubusercontent.com/13399527/147777644-261a8189-54aa-4be4-9fb1-1728c3dd6513.png)

The leading phrase "Keep all rows that satisfy" makes it clear what the expression is for. Should we add a similar phrase for other transformers that use expressions?

**Comment by thomascastleman** [comment]
@schanzer @shriram to weigh in

**Comment by shriram** [comment]
Oooh, that would be really nice if it could be done! It would also make each transformer more self-descriptive, reducing the need to ever look at documentation (which is always a win).

**Comment by schanzer** [comment]
@thomascastleman I think this is an excellent idea. Here's what I would put for the transformers:

**Transform**
For each row, replace the value of attribute `xyz` with the result of the expression:

**Build**
For each row, add the attribute `xyz` with the result of the expression:

My head isn't wrapped around the others as much, since we don't use them at all (yet!). Curious what you'd all propose for those?

**Comment by thomascastleman** [comment]
The only others that use formulas are Sort and Reduce:

- Sort has a single formula which is evaluated at each row and that value is used to sort the rows.

- Reduce has two formulas, one which determines the starting value of the accumulator, and another which is the formula for computing the next value of the accumulator given the current value.

**Comment by schanzer** [comment]
`Sort` - Sort the rows in this table by a value, which is computed by: <blank>
`Reduce` - (1) Starting with: <blank>, (2) compute the next value for each row by: <blank>

**Comment by thomascastleman** [comment]
Closed by #235
