### ISSUE TITLE
name + purpose statement UI

### ISSUE THREAD

**Issue by thomascastleman** [P-bibs/codap-transformers#231]
Some of the feedback we got was to match the design recipe template as close as possible. For Bootstrap purposes, would it help if the dropdown labeled "Save This Transformer" were moved up to the top of the UI, just below the transformer dropdown?  This could make name / purpose statement more explicitly the initial steps before filling out the "body" of the transformer.

@schanzer @shriram

**Comment by shriram** [comment]
Deferring to @schanzer as a pedagogic decision that ties closely to how he expects the revised Bootstrap curriculum to use it.

I will say though, IMO: I think with CODAP/T, the purpose statement can and should somewhat take a back seat. First, we're building for kids who are not very keyboard-ready, so we want to minimize typing. Second, the function body is not an arbitrary sea of characters: it's already quite structured and full of descriptive entries (rather than mysterious variable names like `t`), so it's not that hard to read off.

**Comment by schanzer** [comment]
@thomascastleman Below is a screenshot of the paper-and-pencil scaffold we have for helping kids build transformers:

![image](https://user-images.githubusercontent.com/77126/147990777-94c87634-7cdb-4319-a735-ac3da0d49fed.png)

So in this scenario, the name definitely belongs at the top -- but the purpose should stay close to the formula expression. Something Rachel Tabak (who's leading the CODAP curriculum work) and I have identified is that Transformers require students to think in terms of _Table transformations_ ("what does this transformer do to a table?") and _Row computations_ ("what happens to a single row of the table?"). And when these get blurred, it gets messy.

Linking the purpose to the formula expression feels like the right way to go here, if this is something that can actually be done on a per-transformer basis. (I know that not every transformer has an expression!)

**Comment by thomascastleman** [comment]
It makes sense that for transformers with formulas, there are two separate computations to think about. But, doesn't linking the purpose statement to the formula in some transformers and to the transformer itself in others (those without formulas) run the risk of blurring that line for students?

If we decide to attach purpose statements to formulas where applicable, there's still the question of where things go--does the name always go up top, and the purpose right below it (if no formula) or above the formula (if applicable)?

**Comment by schanzer** [comment]
The name always goes at the top, since it's the name of the _transformer_.  The purpose should go above the formula (if applicable), since it describes the formula that's appled to each _row_.

**Comment by thomascastleman** [comment]
And so for transformers that don't have a formula, should the purpose statement go at the top below the name? Or remain near the bottom where it is now?

**Comment by schanzer** [comment]
Let's keep it at the bottom, to be consistent with the location for Transformers that _do_ have formulas.

**Comment by retabak** [comment]
Finally taking a close look at the UI. It's looking good! 

Two questions coming to mind initially:

1. The DR templates goes in this order: **_name -> contract -> purpose statement -> expression_** ... but the UI goes in this order: **_name -> purpose statement -> contract -> expression_**

Can we put the purpose statement after the contract in the UI? Or: is there a reason that it's before the contract? We definitely want the DR template and the UI to walk our students through the same steps in the same order. (Maybe it's the DR that needs to change?)

2. I'm noticing some inconsistency in the language used for different transformers on the UI. (See yellow highlights on the screenshot below.) Namely, “filter” says “How to Filter” but Transform and Build say “Formula for…” ? (And “Sort” says “Key expression” in this same position.) Can we be consistent? Or, alternatively, is there a reason we’re not being consistent?

![image](https://user-images.githubusercontent.com/87144723/159992181-3b41cffa-3f00-448b-bd33-e0f8d3c3803b.png)
![image](https://user-images.githubusercontent.com/87144723/159992323-153bd83d-47e0-4575-a8e7-0bff22fa63e7.png)

I am going to play around more and will let you know when / if I notice other things!

**Comment by stardust66** [comment]
> 1. The DR templates goes in this order: **_name -> contract -> purpose statement -> expression_** ... but the UI goes in this order: **_name -> purpose statement -> contract -> expression_**

Thanks for the review! This should be fixed now.

**Comment by thomascastleman** [comment]
@retabak I agree we could make the language a bit more consistent. Shall we change Filter to say "Formula to Filter By" and Sort to say "Formula to Sort By" (and "Attribute to Sort By" for the other sort variant, see #238)?

**Comment by retabak** [comment]
@thomascastleman I like this better!
