### ISSUE TITLE
updating many contexts causes crash

### ISSUE THREAD

**Issue by thomascastleman** [P-bibs/codap-transformers#95]
- Create several (>6 or so) transformed datasets off of one input dataset
- Apply an update to the input table

I get:
Unhandled Rejection (TypeError): responses is not iterable

This happens in `updateContextWithDataSet`, it looks like `responses` is `undefined` in 
```ts
const responses = await callMultiple(requests);
```

@stardust66 Any idea what's happening here?

**Comment by stardust66** [comment]
What transformation did you use for this?

**Comment by thomascastleman** [comment]
I tried it with partition and also just copying the input 6 times. I haven't tested other transformations but I think it has to do with the large number of tables being updated.

**Comment by stardust66** [comment]
Hmm, copying the input lots of times doesn't seem to do it on my end. Not sure if this is related but have you pulled from the codap fork recently?

**Comment by thomascastleman** [comment]
Hmm. That's weird. I tried it on both `experimental` and `for-review` at the latest commits and it happens for me. Are you on CODAP-flow `main`? @P-bibs can you reproduce my bug?

**Comment by stardust66** [comment]
Yes I'm on `main`. Trying partitioning by Age now

**Comment by P-bibs** [comment]
I'm not observing this bug when copying a table 6 times and then updating the original. Using latest version of CODAP-flow and our CODAP fork.

**Comment by thomascastleman** [comment]
Are you both using the Microdata People table? Or a comparably large dataset? I notice it's not happening with smaller datasets.

I'm also noticing that the times it fails, it seems to alternate between deleting 0 and some number of cases as it's updating:

![deleted](https://user-images.githubusercontent.com/13399527/123296718-e4220980-d4e4-11eb-8b68-7a51d662a8f0.png)

**Comment by P-bibs** [comment]
Yep I used the microdata portal. Maybe we should try testing across
browsers?

**Comment by thomascastleman** [comment]
Weird, it does seem to work in Firefox but not Brave. Any others?

**Comment by thomascastleman** [comment]
I no longer observe this on small updates (6-8 or so tables) but can reproduce this in Brave when I partition People by Boundaries and then make an update. It is the same `Unhandled Rejection (TypeError): responses is not iterable` from `src/utils/codapPhone/index.ts:727` at the end of the update.

**Comment by thomascastleman** [comment]
I do observe this on Chrome as well, with this test:

1. Open a Microdata table
2. Partition on Boundaries (and go through with it)
3. Drag an attribute in the input dataset

Can you all confirm this on Chrome? @stardust66 @P-bibs 

You can use the [staging build](https://codap.concord.org/releases/staging/static/dg/en/cert/index.html) to get around our cross-origin iframe issue with Partition (and just check the console).

**Comment by P-bibs** [comment]
Hmm I still can't reproduce this on Chrome (on the staging build). Not sure what could be going on

**Comment by thomascastleman** [comment]
Are you waiting until the end for all the updates to go through? I'm only getting a crash once the last table updates and it takes some time.

**Comment by P-bibs** [comment]
It's a little hard to tell whether the update is done because they're all stacked but I've given about 1.5x as long as it took to do the initial partition and everything still seems to be fine (no errors)
